{
 "title": "SRE - Service Levels",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Service Level Indicator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Availability SLI ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{response_code=~\"2..|3..\",cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[5m])) \n/ \nsum(rate(istio_requests_total{cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency SLI",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(istio_request_duration_milliseconds_bucket{le=\"1000\",response_code=~\"2..|3..\",cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[5m])) \n/ \nsum(rate(istio_request_duration_milliseconds_bucket{response_code=~\"2..|3..\",cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate SLI ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{response_code=~\"5..|4..\",cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[5m])) \n/ \nsum(rate(istio_requests_total{cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Service Level Objective", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Availability SLO - 99.95% - status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(istio_requests_total{response_code=~\"2..|3..\",cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[30d])) \n/ \nsum(rate(istio_requests_total{cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[30d])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability - quantity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(istio_requests_total{response_code=~\"2..|3..\",cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[30d])) \n/ \nsum(rate(istio_requests_total{cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[30d])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency SLO - 99,95% - status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (sum(rate(istio_request_duration_milliseconds_bucket{le=\"500\",response_code=~\"2..|3..\",cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[30d])) \n/ \nsum(rate(istio_request_duration_milliseconds_bucket{response_code=~\"2..|3..\",cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[30d])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency - quantity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (sum(rate(istio_request_duration_milliseconds_bucket{le=\"500\",response_code=~\"2..|3..\",cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[30d])) \n/ \nsum(rate(istio_request_duration_milliseconds_bucket{response_code=~\"2..|3..\",cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[30d])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate SLO - 99,95% - status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (sum(rate(istio_requests_total{response_code=~\"5..|4..\",cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[30d])) \n/ \nsum(rate(istio_requests_total{cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[30d])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate - quantity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (sum(rate(istio_requests_total{response_code=~\"5..|4..\",cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[30d])) \n/ \nsum(rate(istio_requests_total{cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[30d])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true
  },
  {
   "title": "Availability EB - Burn Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (sum(rate(istio_requests_total{response_code=~\"2..|3..\",cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[30d])) \n/ \nsum(rate(istio_requests_total{cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[30d])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability - quantity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (sum(rate(istio_requests_total{response_code=~\"2..|3..\",cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[30d])) \n/ \nsum(rate(istio_requests_total{cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[30d])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency EB - Burn Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (100 - (sum(rate(istio_request_duration_milliseconds_bucket{le=\"500\",response_code=~\"2..|3..\",cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[30d])) \n/ \nsum(rate(istio_request_duration_milliseconds_bucket{response_code=~\"2..|3..\",cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[30d])) * 100))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency - quantity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (100 - (sum(rate(istio_request_duration_milliseconds_bucket{le=\"500\",response_code=~\"2..|3..\",cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[30d])) \n/ \nsum(rate(istio_request_duration_milliseconds_bucket{response_code=~\"2..|3..\",cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[30d])) * 100))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate  EB - Burn Rate - status ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum(rate(istio_requests_total{response_code=~\"5..|4..\",cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[30d])) \n/ \nsum(rate(istio_requests_total{cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[30d])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate - quantity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (100 - (sum(rate(istio_requests_total{response_code=~\"5..|4..\",cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[30d])) \n/ \nsum(rate(istio_requests_total{cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[30d])) * 100))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}