{
 "title": "SRE - Service Levels - Application",
 "tags": [ "SRE" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "window",
    "label": "Window",
    "query": "5m, 15m, 30m, 1h, 6h, 12h, 24h, 7d, 30d, 60d"
   }
  ]
 },
 "panels": [
  { "title": "Service Level Indicator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Availability SLI ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{response_code=~\"2..|3..\",cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[${window}])) \n/ \nsum(rate(istio_requests_total{cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[${window}]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency SLI",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(istio_request_duration_milliseconds_bucket{le=\"1000\",response_code=~\"2..|3..\",cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[${window}])) \n/ \nsum(rate(istio_request_duration_milliseconds_bucket{response_code=~\"2..|3..\",cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[${window}]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate SLI ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{response_code=~\"5..\",cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[${window}])) \n/ \nsum(rate(istio_requests_total{cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[${window}]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Service Level Objective", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Availability - quantity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(istio_requests_total{response_code=~\"2..|3..\",cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[${window}])) \n/ \nsum(rate(istio_requests_total{cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[${window}])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency - quantity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (sum(rate(istio_request_duration_milliseconds_bucket{le=\"500\",response_code=~\"2..|3..\",cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[${window}])) \n/ \nsum(rate(istio_request_duration_milliseconds_bucket{response_code=~\"2..|3..\",cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[${window}])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate - quantity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (sum(rate(istio_requests_total{response_code=~\"5..\",cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[${window}])) \n/ \nsum(rate(istio_requests_total{cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[${window}])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Error Budget", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Availability - quantity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (sum(rate(istio_requests_total{response_code=~\"2..|3..\",cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[${window}])) \n/ \nsum(rate(istio_requests_total{cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[${window}])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency - quantity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (100 - (sum(rate(istio_request_duration_milliseconds_bucket{le=\"500\",response_code=~\"2..|3..\",cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[${window}])) \n/ \nsum(rate(istio_request_duration_milliseconds_bucket{response_code=~\"2..|3..\",cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[${window}])) * 100))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate - quantity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (100 - (sum(rate(istio_requests_total{response_code=~\"5..\",cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[${window}])) \n/ \nsum(rate(istio_requests_total{cluster=\"prod\",destination_service_name=\"mfe-mpf-app-prod\"}[${window}])) * 100))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}